---
name: Build Python

on:
  workflow_call:
    inputs:
      project_path:
        description: 'Project directory path (for monorepo support)'
        required: false
        type: string
        default: '.'
      python_version:
        description: 'Python version'
        required: false
        type: string
        default: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Upgrade pip
        working-directory: ${{ inputs.project_path }}
        run: python -m pip install -U pip

      - name: Install dependencies and build
        working-directory: ${{ inputs.project_path }}
        run: |
          if [ -f "pyproject.toml" ]; then
            pip install -U build
            python -m build
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt / pyproject.toml found. Skipping dependency install."
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-python
          path: |
            ${{ inputs.project_path }}/dist/
            ${{ inputs.project_path }}/.venv/
          retention-days: 1
          if-no-files-found: ignore
