---
name: Security - Secret Scanning

on:
  workflow_call:
    inputs:
      project_path:
        description: 'Project directory path (for monorepo support)'
        required: false
        type: string
        default: '.'
      security_scanner:
        description: 'Scanner to use (trivy or gitleaks)'
        required: false
        type: string
        default: 'trivy'
      severity:
        description: 'Severity levels to report'
        required: false
        type: string
        default: 'HIGH,CRITICAL'

jobs:
  secrets-trivy:
    if: inputs.security_scanner == 'trivy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy secret scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ inputs.project_path }}
          scanners: 'secret'
          severity: ${{ inputs.severity }}
          format: 'json'
          output: 'secrets-report.json'

      - name: Upload secret scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: secrets-report-trivy
          path: secrets-report.json
          retention-days: 7

  secrets-gitleaks:
    if: inputs.security_scanner == 'gitleaks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_ENABLE_SUMMARY: true
        with:
          args: --redact --source=${{ inputs.project_path }} --report-path=gitleaks-report.json --report-format=json --no-git

      - name: Upload secret scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: secrets-report-gitleaks
          path: gitleaks-report.json
          retention-days: 7
