---
# OWASP SPVS: Develop Phase - Build artifacts
# Build Templates - Language-specific build job templates
#
# Provides reusable build job templates for Node.js, Python, and PHP applications.
# Use the appropriate template based on your application's language. Supports monorepo
# configurations and common package managers.
#
# Quick Start:
#   Node.js:
#     build-app:
#       extends: .build:node
#       variables:
#         NODE_VERSION: "20"
#         PACKAGE_MANAGER: "pnpm"
#
#   Python:
#     build-app:
#       extends: .build:python
#       variables:
#         PYTHON_VERSION: "3.12"
#
#   PHP:
#     build-app:
#       extends: .build:php
#       variables:
#         PHP_VERSION: "8.3"
#
# Variables - Node.js:
#   NODE_VERSION: "20"                  # Node.js version (default: "20")
#   PACKAGE_MANAGER: "npm"              # Package manager: "npm", "yarn", "pnpm" (default: "npm")
#   PROJECT_PATH: ""                    # Monorepo: subproject path (e.g., "frontend")
#
# Variables - Python:
#   PYTHON_VERSION: "3.12"              # Python version (default: "3.12")
#   PROJECT_PATH: ""                    # Monorepo: subproject path (e.g., "backend")
#
# Variables - PHP:
#   PHP_VERSION: "8.3"                  # PHP version (default: "8.3")
#   PROJECT_PATH: ""                    # Monorepo: subproject path (e.g., "api")
#
# Variables - Pipeline Control:
#   RUN_ON_BRANCHES: "false"            # Run on all branches or MR/main only (default: "false")
#
# Supported Package Managers:
#   Node.js:
#     - npm: Uses npm ci and npm run build
#     - yarn: Uses yarn install --frozen-lockfile and yarn build
#     - pnpm: Uses pnpm install --frozen-lockfile and pnpm build
#
#   Python:
#     - pip: Installs from requirements.txt
#     - build: Uses pyproject.toml for building packages
#
#   PHP:
#     - composer: Uses composer install with optimized autoloader
#
# Artifacts:
#   Node.js: .output/, .nuxt/, dist/, node_modules/
#   Python: dist/, .venv/
#   PHP: vendor/
#   Expiration: 1 day
#
# Monorepo Support:
#   Set PROJECT_PATH to build specific component:
#   build-frontend:
#     extends: .build:node
#     variables:
#       PROJECT_PATH: "frontend"
#       PACKAGE_MANAGER: "pnpm"
#
# Custom Build Steps:
#   Override script section for custom build logic:
#   build-app:
#     extends: .build:node
#     script:
#       - npm ci
#       - npm run custom-build-script

# Hidden base job to be extended by examples/projects
.build:base:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$RUN_ON_BRANCHES == "true"'
  artifacts:
    expire_in: 1 day

.build:node:
  extends: .build:base
  image: node:${NODE_VERSION:-20}-alpine
  before_script:
    - cd "${PROJECT_PATH:-.}"
  script:
    - corepack enable
    - |
      if [ "${PACKAGE_MANAGER:-npm}" = "pnpm" ]; then
        pnpm install --frozen-lockfile
        pnpm build
      elif [ "${PACKAGE_MANAGER:-npm}" = "yarn" ]; then
        yarn install --frozen-lockfile
        yarn build
      else
        npm ci
        npm run build
      fi
  artifacts:
    paths:
      - ${PROJECT_PATH:-.}/.output/
      - ${PROJECT_PATH:-.}/.nuxt/
      - ${PROJECT_PATH:-.}/dist/
      - ${PROJECT_PATH:-.}/node_modules/

.build:python:
  extends: .build:base
  image: python:${PYTHON_VERSION:-3.12}-slim
  before_script:
    - cd "${PROJECT_PATH:-.}"
  script:
    - python -m pip install -U pip
    - |
      if [ -f "pyproject.toml" ]; then
        pip install -U build
        python -m build
      elif [ -f "requirements.txt" ]; then
        pip install -r requirements.txt
      else
        echo "No requirements.txt / pyproject.toml found. Skipping dependency install."
      fi
  artifacts:
    paths:
      - ${PROJECT_PATH:-.}/dist/
      - ${PROJECT_PATH:-.}/.venv/

.build:php:
  extends: .build:base
  image: php:${PHP_VERSION:-8.3}-cli
  before_script:
    - cd "${PROJECT_PATH:-.}"
  script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction --prefer-dist --optimize-autoloader
  artifacts:
    paths:
      - ${PROJECT_PATH:-.}/vendor/
