include:
  - local: /templates/workflow.yml

# Pipeline stages aligned with OWASP Secure Pipeline Verification Standard (SPVS)
# https://owasp.org/www-project-spvs/
stages:
  # OWASP SPVS: Develop Phase - Secure coding and continuous reviews
  - source        # Source code security (secrets, dependencies, SAST)
  - build         # Build artifacts
  - test          # Unit and integration tests

  # OWASP SPVS: Integrate Phase - Automated validation and artifact integrity
  - package       # Package and scan artifacts (container, IaC)

  # OWASP SPVS: Release Phase - Final validations and secure deployment
  - stage         # Deploy to staging environment
  - verify        # Verification testing (DAST, E2E, acceptance)
  - deploy        # Deploy to production

  # OWASP SPVS: Operate Phase - Continuous monitoring and incident response
  - operate       # Operations and monitoring
  - report        # Security reporting and metrics

default:
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

variables:
  # Polyglot selector (node|python|php|java|generic)
  LANGUAGE: "generic"

  # Security tool selection (trivy|specialized)
  # trivy: Use Trivy for all security scanning (secrets, dependencies, SAST, IaC, container)
  # specialized: Use specialized tools (Gitleaks, language-specific scanners, Semgrep)
  SECURITY_SCANNER: "trivy"

  # SAST tool selection (only applies when SECURITY_SCANNER=specialized or for mixed approach)
  # semgrep: Use Semgrep for comprehensive SAST
  # trivy: Use Trivy for basic SAST/misconfiguration detection
  SAST_TOOL: "semgrep"

  # Feature toggles (Teams können aktivieren/deaktivieren)
  ENABLE_SECRETS: "true"
  ENABLE_DEPENDENCY_SCAN: "true"
  ENABLE_SAST: "true"
  ENABLE_CONTAINER_SCAN: "false"
  ENABLE_IAC_SCAN: "false"
  ENABLE_DAST: "false"
  ENABLE_E2E: "false"
  ENABLE_PERF_TESTS: "false"

  # Pipeline behaviour
  RUN_ON_BRANCHES: "false"

  # GitOps
  GITOPS_REPO: ""
  GITOPS_PATH: "values.yaml"
  GITOPS_IMAGE_TAG_YQ_PATH: ".image.tag"  # default: .image.tag
  GITOPS_COMMIT_MESSAGE: "Promote ${CI_COMMIT_SHORT_SHA}"

  # DAST / Validation
  STAGING_URL: ""

  # Compliance/Gating policy (ISO 27001 / NIS2 / OWASP ASVS)
  # "strict": fail in MR + default branch
  # "permissive": allow_failure on non-default branches
  SECURITY_POLICY: "strict"

  # Trivy gating (container scan)
  TRIVY_SEVERITY: "CRITICAL,HIGH"
  TRIVY_EXIT_CODE: "1"

# ---------- Common rule sets ----------
.rules_mr_or_default: &rules_mr_or_default
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.rules_default_manual: &rules_default_manual
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - when: never

# "strict" = blockierend auf MR+default branch
.security_allow_failure:
  rules:
    - if: '$SECURITY_POLICY == "permissive" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: on_success
      allow_failure: true
    - when: on_success
      allow_failure: false

# Placeholders / hooks: Teams können weitere Jobs hinzufügen, ohne Stages zu ändern.
