include:
  - local: /templates/workflow.yml

stages:
  - preflight
  - build
  - test
  - security-scan
  - security-analysis
  - deploy-staging
  - validate
  - deploy-production
  - monitor
  - report

default:
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

variables:
  # Polyglot selector (node|python|php|java|generic)
  LANGUAGE: "generic"

  # Feature toggles (Teams können aktivieren/deaktivieren)
  ENABLE_SECRETS: "true"
  ENABLE_DEPENDENCY_SCAN: "true"
  ENABLE_SAST: "true"
  ENABLE_CONTAINER_SCAN: "false"
  ENABLE_IAC_SCAN: "false"
  ENABLE_DAST: "false"
  ENABLE_E2E: "false"
  ENABLE_PERF_TESTS: "false"

  # Pipeline behaviour
  RUN_ON_BRANCHES: "false"

  # GitOps
  GITOPS_REPO: ""
  GITOPS_PATH: "values.yaml"
  GITOPS_IMAGE_TAG_YQ_PATH: ".image.tag"  # default: .image.tag
  GITOPS_COMMIT_MESSAGE: "Promote ${CI_COMMIT_SHORT_SHA}"

  # DAST / Validation
  STAGING_URL: ""

  # Compliance/Gating policy (ISO 27001 / NIS2 / OWASP ASVS)
  # "strict": fail in MR + default branch
  # "permissive": allow_failure on non-default branches
  SECURITY_POLICY: "strict"

  # Trivy gating (container scan)
  TRIVY_SEVERITY: "CRITICAL,HIGH"
  TRIVY_EXIT_CODE: "1"

# ---------- Common rule sets ----------
.rules_mr_or_default: &rules_mr_or_default
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.rules_default_manual: &rules_default_manual
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - when: never

# "strict" = blockierend auf MR+default branch
.security_allow_failure:
  rules:
    - if: '$SECURITY_POLICY == "permissive" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: on_success
      allow_failure: true
    - when: on_success
      allow_failure: false

# Placeholders / hooks: Teams können weitere Jobs hinzufügen, ohne Stages zu ändern.
