---
# Hidden base job to be extended by examples/projects
.build:base:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$RUN_ON_BRANCHES == "true"'
  artifacts:
    expire_in: 1 day

.build:node:
  extends: .build:base
  image: node:${NODE_VERSION:-20}-alpine
  script:
    - corepack enable
    - |
      if [ "${PACKAGE_MANAGER:-npm}" = "pnpm" ]; then
        pnpm install --frozen-lockfile
        pnpm build
      elif [ "${PACKAGE_MANAGER:-npm}" = "yarn" ]; then
        yarn install --frozen-lockfile
        yarn build
      else
        npm ci
        npm run build
      fi
  artifacts:
    paths:
      - .output/
      - .nuxt/
      - dist/
      - node_modules/

.build:python:
  extends: .build:base
  image: python:${PYTHON_VERSION:-3.12}-slim
  script:
    - python -m pip install -U pip
    - |
      if [ -f "pyproject.toml" ]; then
        pip install -U build
        python -m build
      elif [ -f "requirements.txt" ]; then
        pip install -r requirements.txt
      else
        echo "No requirements.txt / pyproject.toml found. Skipping dependency install."
      fi
  artifacts:
    paths:
      - dist/
      - .venv/

.build:php:
  extends: .build:base
  image: php:${PHP_VERSION:-8.3}-cli
  script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction --prefer-dist --optimize-autoloader
  artifacts:
    paths:
      - vendor/
