---
workflow:
  rules:
    # Pipelines für MRs immer
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    # Pipelines für Default Branch immer
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    # Optional: tags/releases
    - if: '$CI_COMMIT_TAG'
      when: always
    # Sonst nur wenn explizit enabled
    - if: '$RUN_ON_BRANCHES == "true"'
      when: always
    - when: never
