---
name: Test Python

on:
  workflow_call:
    inputs:
      project_path:
        description: 'Project directory path (for monorepo support)'
        required: false
        type: string
        default: '.'
      python_version:
        description: 'Python version'
        required: false
        type: string
        default: '3.12'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        working-directory: ${{ inputs.project_path }}
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage
        working-directory: ${{ inputs.project_path }}
        run: pytest -q --junitxml=junit.xml --cov=. --cov-report=xml:coverage.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-python
          path: |
            ${{ inputs.project_path }}/junit.xml
            ${{ inputs.project_path }}/coverage.xml
          retention-days: 7
          if-no-files-found: ignore

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ${{ inputs.project_path }}/junit.xml
          check_name: Python Test Results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ${{ inputs.project_path }}/coverage.xml
          flags: python
          fail_ci_if_error: false
